name: Release Released

on:
  release:
    types: [released]
 
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    
    steps:
      - env:
          RELEASE: ${{ env.GITHUB_REF }}
        run: |
          echo RELEASE=$RELEASE
          env
